InventoryManager/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name = 'index')
]

InventoryManager/product/urls.py
from django.urls import path
from . import views
from InventoryManager.withdrawal import views as wdviews

app_name = 'product'
urlpatterns = [
    path('', views.product_list, name = 'list'),
    path('search/', views.product_search, name='search'),
    path('add/', views.product_add, name = 'add'),
    path('detail/<int:pk>/', views.product_detail, name='detail'),
    path('delete/<int:pk>/', views.product_delete, name = 'delete'),



    path('<int:pk>/withdrawal/', wdviews.withdrawal_product, name = 'withdrawal')
    
]

InventoryManager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('InventoryManager.product.urls')),
    path('withdrawals/', include('InventoryManager.withdrawal.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

InventoryManager/withdrawal/urls.py
from django.urls import path
from . import views


app_name = 'withdrawal'
urlpatterns = [
    path('', views.withdrawal_log, name = 'log')
]

InventoryManager/category/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category_name = models.CharField('Category', max_length = 100)

    def __str__(self):
        return self.category_name 

InventoryManager/core/models.py
from django.db import models

# Create your models here.

InventoryManager/entry/models.py
from django.db import models

# Create your models here.

InventoryManager/product/models.py
from django.db import models
from InventoryManager.category.models import Category
from django.contrib.auth.models import User

class Product(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    category = models.ForeignKey(Category, on_delete = models.CASCADE, verbose_name = 'Category')
    product_name = models.CharField('Product', max_length = 255)
    product_description = models.TextField(null = True)
    product_quantity = models.IntegerField(default = 0)
    product_image = models.ImageField(upload_to = 'product/', null=True)
    
    def __str__(self):
        return self.product_name

InventoryManager/withdrawal/models.py
from django.db import models
from InventoryManager.product.models import Product
from django.contrib.auth.models import User


class WithdrawalProduct(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    withdrawal_time = models.DateTimeField(auto_now=True)
    withdrawal_quantity = models.IntegerField()
    withdrawal_reason = models.TextField(max_length=255)

    def __str__(self):
        return str(self.product)

InventoryManager/product/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        widgets = {'user':forms.HiddenInput()}

InventoryManager/withdrawal/forms.py
from django import forms
from .models import WithdrawalProduct

class WithdrawalForm(forms.ModelForm):
    class Meta:
        model = WithdrawalProduct
        fields = '__all__'
        widgets = {'user':forms.HiddenInput()}

InventoryManager/category/views.py
from django.shortcuts import render

# Create your views here.

InventoryManager/core/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'base.html')

InventoryManager/entry/views.py
from django.shortcuts import render

# Create your views here.

InventoryManager/product/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.db.models import Q
from .models import Product
from .forms import ProductForm
from InventoryManager.category.models import Category
from django.http import Http404



def product_list(request):
    category = Category.objects.filter(user = request.user.id)
    products = Product.objects.filter(user = request.user.id)
    return render(request, 'product_list.html', {'products':products, 'category':category})

def product_add(request):
    form = ProductForm()
    if request.method == 'POST':
        form = ProductForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            data_from_form = Product(
                user = form.cleaned_data['user'],
                category = form.cleaned_data['category'],
                product_name = form.cleaned_data['product_name'],
                product_description = form.cleaned_data['product_description'],
                product_quantity = form.cleaned_data['product_quantity'],
                product_image = form.cleaned_data['product_image'],
              
            )
            data_from_form.save()
            # Insert success Message here
            return redirect('product:list')
    return render(request, 'productAddModal.html', {'form':form,})

def product_detail(request, pk):
    category = Category.objects.filter(user = request.user.id)
    product = get_object_or_404(Product, pk = pk)
    return render(request, 'product_detail.html', {'product':product, 'category':category})


def product_search(request):
    category = Category.objects.filter(user = request.user.id)
    products = Product.objects.filter(user = request.user.id)
    if request.method == 'GET':
        search = request.GET.get('search')
        products = products.filter(product_name__icontains = search)
    return render(request, 'product_list.html', {'products':products, 'category':category})


def product_delete(request, pk):
    product = get_object_or_404(Product, pk = pk)
    if product.user != request.user:
        raise Http404
    # form = ProductForm(request.POST or None, request.FILES or None, instance = product)
    if request.method == 'POST':
        product.delete()
        return redirect('product:list')
    return render(request, 'productDeleteModal.html', {'product':product})

InventoryManager/withdrawal/views.py
from django.shortcuts import render, get_object_or_404, redirect
from InventoryManager.product.models import Product
from .models import WithdrawalProduct
from .forms import WithdrawalForm

def withdrawal_product(request, pk):
    product = get_object_or_404(Product, pk = pk)
    form = WithdrawalForm()
    if request.method == 'POST':
        form = WithdrawalForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            data_from_form = WithdrawalProduct(
                user = form.cleaned_data['user'],
                product = form.cleaned_data['product'],
                withdrawal_quantity = form.cleaned_data['withdrawal_quantity'],
                withdrawal_reason = form.cleaned_data['withdrawal_reason']
            )
            product.product_quantity -= data_from_form.withdrawal_quantity
            product.save()
            data_from_form.save()
            return redirect('product:list')
    
    return render(request, 'withdrawalProductModal.html', {'form':form, 'product':product})

def withdrawal_log(request):
    withdrawals = WithdrawalProduct.objects.filter(user = request.user)
    return render(request, 'withdrawal_log.html', {'withdrawals':withdrawals})

InventoryManager/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.5.7/dist/css/uikit.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
{% block css %}{% endblock css %}
<style>
    #loading {
  display: block;
  position: absolute;
  top: 0;
  left: 0;
  z-index: 100;
  width: 100vw;
  height: 100vh;
  background-color: rgba(192, 192, 192, 0.5);
  background-image: url("https://onlinelibrary.wiley.com/ux3/widgets/publication-content/images/spinner.gif");
  background-repeat: no-repeat;
  background-position: center;
  background-size: 20em;
}
</style>
<title>Simple Inventory Manager|{% block title %}{% endblock title %}</title>
</head>
<body>
    {% block navbar %} {% endblock navbar %}
    <div class="uk-container">{% block main %}{% endblock main %}</div> 
    {% block js %}{% endblock js %}
    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.5.7/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.5.7/dist/js/uikit-icons.min.js"></script>
    <div id="loading"></div>
</body>
</html>

InventoryManager/core/templates/includes/_navbar.html
<nav style="background-color: rgba(24, 24, 24, 0.904); color: white;" class="uk-navbar-container uk-margin" uk-navbar>
    <div class="nav-overlay uk-navbar-left">
        <a style="color: rgb(214, 214, 214);" class="uk-navbar-item uk-logo" href="{% url 'product:list' %}">SIM</a>
        
    </div>
    <div class="nav-overlay uk-navbar-right">
        <ul class="uk-navbar-nav nav-overlay uk-visible@s">
            <li >
                <a href="#">Actions</a>
                <div class="uk-navbar-dropdown ">
                    <ul class="uk-nav uk-navbar-dropdown-nav ">
                        
                        <li><a href="#" uk-toggle="target: #productAddModal">Add New Product</a></li>
                        <li><a href="#">Item</a></li>
                    </ul>
                </div>
            </li>
            <li>
                <a href="#">Logs</a>
                <div class="uk-navbar-dropdown">
                    <ul class="uk-nav uk-navbar-dropdown-nav">
                        
                        <li><a href="{% url 'withdrawal:log' %}">Withdrawals</a></li>
                        <li><a href="#">Entries Log</a></li>
                    </ul>
                </div>
            </li>
        </ul>
        <a class="uk-navbar-toggle" uk-search-icon uk-toggle="target: .nav-overlay; animation: uk-animation-fade" href="#"></a>
    </div>
    
    <a href="#" class="uk-navbar-toggle uk-hidden@s" uk-navbar-toggle-icon uk-toggle="target: #sidenav"></a>
   

    
    {% block search %}
        {% include 'includes/_search.html' %}
    {% endblock search %}
        
   
</nav>

<div id="sidenav" uk-offcanvas="flip: true" class="uk-offcanvas">
    <div class="uk-offcanvas-bar">
        <div>
            <div class="uk-width-1-1">
              <ul class="uk-nav-parent-icon uk-nav-primary" uk-nav>
                <li class="uk-parent uk-active">
                  <a href="#">Actions</a>
                  <ul class="uk-nav-sub">
                    <li><a href="#" uk-toggle="target: #productAddModal">Add New Product</a></li>
                    <li><a href="#">Item</a></li>
                   
                  </ul>
                </li>
              </ul>
              <ul class="uk-nav-parent-icon uk-nav-primary" uk-nav>
                <li class="uk-parent uk-active">
                  <a href="#">Logs</a>
                  <ul class="uk-nav-sub">
                    <li><a href="#">Withdrawals</a></li>
                    <li><a href="#">Entries</a></li>
                
                  </ul>
                </li>
              </ul>
            </div>
          </div>
    </div>
</div>

InventoryManager/core/templates/includes/_search.html
<div class="nav-overlay uk-navbar-left uk-flex-1" hidden>
    <div class="uk-navbar-item uk-width-expand">
        <form class="uk-search uk-search-navbar uk-width-1-1" method="get" action=" {% url 'product:search' %} ">
            
            <input class="uk-search-input" type="search" name="search" placeholder="Search..." autofocus>
        </form>
    </div>
    <a class="uk-navbar-toggle" uk-close uk-toggle="target: .nav-overlay; animation: uk-animation-fade" href="#"></a>
</div>

InventoryManager/product/templates/productAddModal.html
<div id="productAddModal" uk-modal>
    <div class="uk-modal-dialog uk-modal-body">
        <h2 class="uk-modal-title"></h2>
        <form method="post" enctype="multipart/form-data" action=" {% url 'product:add' %} " >
            {% csrf_token %}
            <fieldset class="uk-fieldset">

                <legend class="uk-legend"> <b>Product</b><span style="font-weight: 300; color: rgb(120, 122, 124);"> Form</span> </legend>
        
                <div class="uk-margin">
                    <input class="uk-input" id="id_product_name" name="product_name" type="text" placeholder="Product Name">
                </div>
        
                <div class="uk-margin">
                    <select class="uk-select" id="id_category" name="category">
                        <option>Category</option>
                        {% for obj in category  %}
                        <option value="{{obj.id}}">{{obj}}</option>
                        {% endfor %}
                    </select>
                </div>
                
                <div class="uk-margin">
                    <textarea id="id_product_description" name="product_description" class="uk-textarea" rows="5" placeholder="Product Description"></textarea>
                </div>
                <div class="uk-margin">
                    <input class="uk-input" id="id_product_quantity" name="product_quantity" type="number" placeholder="Product Quantity">
                </div>
                <div class="uk-margin">
                    <div uk-form-custom>
                        <input type="file" name="product_image" id="id_product_image">
                        <button class="uk-button uk-button-default" type="button" tabindex="-1">Select Image</button>
                    </div>
                </div>
        
            </fieldset>
            <input type="text" id="id_user" name="user" hidden value="{{request.user.id}}">
            <button class = "uk-button uk-button-primary" type="submit">Save</button>
        </form>
        
    </div>
</div>


    

InventoryManager/product/templates/productDeleteModal.html
<div id="productDeleteModal" uk-modal>
    <div class="uk-modal-dialog uk-modal-body">
        <h2 class="uk-modal-title"></h2>
        <form method="post" enctype="multipart/form-data" action=" {% url 'product:delete' product.id%} " >
            {% csrf_token %}
            <h2 class="uk-modal-title">Headline</h2>
            <p>Do you really want to delete {{product}}</p>
            <p>If you are sure click on delete</p>
            <p class="uk-text-right">
                <button class="uk-button uk-button-default uk-modal-close" type="button">Cancel</button>
                <button class="uk-button uk-button-danger" type="submit">Delete</button>
            </p>
        </form>
        
    </div>
</div>

InventoryManager/product/templates/product_detail.html
{% extends 'base.html' %}

{% block navbar %}
    {% include 'includes/_navbar.html' %}
{% endblock navbar %}



{% block main %}
    
    <div class="uk-child-width-1-1@s uk-text-center uk-grid-small" uk-grid>
        {{product}}
    </div>
    <div class="uk-child-width-1-1@s uk-text-center uk-grid-small" uk-grid>
        <p>To delete this product <a href="#" uk-toggle="target: #productDeleteModal">Click Here</a></p>
        <p>To withdrawal this product <a href="" uk-toggle="target: #withdrawalProductModal">Click Here</a></p>
    </div>
{% include 'withdrawalProductModal.html' %}
{% include 'productDeleteModal.html' %}
{% include 'productAddModal.html' %}
{% endblock main %}
    

InventoryManager/product/templates/product_list.html
{% extends 'base.html' %}


{% block navbar %}
    {% include 'includes/_navbar.html' %}
{% endblock navbar %}
    
{% block main %}
<div class="uk-child-width-1-4@s uk-text-center uk-grid-small" uk-grid>
    {% for obj in products  %}
    <div>
        <div class="uk-card uk-card-default  ">
            <div class="uk-card-media-top">
                <img src="{{obj.product_image.url}}" style="width: 10em; height: 10em;" alt="">
            </div>
            <div class="uk-card-body uk-card-small uk-card-hover">
                <h3 class="uk-card-title">{{obj.product_name}}</h3>
                <p>Quantity: {{obj.product_quantity}}</p>
                <a href="{% url 'product:detail' obj.id %}"><button  class="uk-button uk-button-primary">Details</button></a>
            </div>
        </div> 
       
    </div>
   
    {% endfor %}
</div>


    
{% include 'productAddModal.html' %}
{% endblock main %}

InventoryManager/product/templates/product_search.html
{% extends 'product_list.html' %}

InventoryManager/withdrawal/templates/withdrawalProductModal.html
<div id="withdrawalProductModal" uk-modal>
    <div class="uk-modal-dialog uk-modal-body">
        <h2 class="uk-modal-title"></h2>
        <form method="post" enctype="multipart/form-data" action=" {% url 'product:withdrawal' product.id %}  " >
            {% csrf_token %}
            <fieldset class="uk-fieldset">
                <legend class="uk-legend"> <b>Withdrawal</b><span style="font-weight: 300; color: rgb(120, 122, 124);"> Form</span> </legend>
                <h4>{{product.product_name}}</h4>
                <div class="uk-margin">
                    <input class="uk-input" id="id_withdrawal_quantity" name="withdrawal_quantity" type="number" placeholder="Withdrawal Quantity">
                </div>
                <div class="uk-margin">
                    <input class="uk-input" id="id_withdrawal_reason" name="withdrawal_reason" type="text" placeholder="Withdrawal Reason">
                </div>
            </fieldset>
            <input type="text" id="id_user" name="user" hidden value="{{request.user.id}}">
            <input  id="id_product" name="product" type="text" hidden value="{{product.id}}">
            <button class = "uk-button uk-button-primary" type="submit">Save</button>
        </form>
        
    </div>
</div>

InventoryManager/withdrawal/templates/withdrawal_log.html
{% extends 'base.html' %}

{% block navbar %}
    {% include 'includes/_navbar.html' %}
{% endblock navbar %}



{% block main %}
    
    <div class="uk-child-width-1-1@s uk-text-center uk-grid-small" uk-grid>
        
        <table class="uk-table uk-table-responsive uk-table-divider">
            <thead>
                <tr>
                    <th>Data</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>User</th>
                    <th>Reason</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in withdrawals %}
                <tr>
                    <td>{{obj.withdrawal_time}}</td>
                    <td>{{obj.product}}</td>
                    <td>{{obj.withdrawal_quantity}}</td>
                    <td>{{obj.user}}</td>
                    <td>{{obj.withdrawal_reason}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
            
    </div>

{% include 'productAddModal.html' %}
{% endblock main %}
    